# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails3-tutorial}
  s.version = "0.4.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wlodek Bzyl"]
  s.date = %q{2010-03-13}
  s.description = %q{Notatki do wykladu Architektura serwisow internetowych
}
  s.email = %q{matwb@univ.gda.pl}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Rakefile",
     "VERSION.yml",
     "lib/config.ru",
     "lib/public/doc/RevisedAutofocusSystem.pdf",
     "lib/public/doc/yuml/ale-kino.url",
     "lib/public/images/InformatykWpracy.gif",
     "lib/public/images/_why.png",
     "lib/public/images/ale-kino/film-kino.png",
     "lib/public/images/ale-kino/film-recenzja-full.png",
     "lib/public/images/ale-kino/film-recenzja.png",
     "lib/public/images/ale-kino/film-seans-kino-full.png",
     "lib/public/images/ale-kino/film-seans-kino.png",
     "lib/public/images/ale-kino/filmy-index-1.png",
     "lib/public/images/ale-kino/filmy-index-scaffold.png",
     "lib/public/images/ale-kino/filmy-show-1.png",
     "lib/public/images/ale-kino/filmy-show-scaffold.png",
     "lib/public/images/algorithm.png",
     "lib/public/images/binary-logic.gif",
     "lib/public/images/bradypus.jpg",
     "lib/public/images/edsger_wybe_dijkstra.jpg",
     "lib/public/images/hfrails_cover.png",
     "lib/public/images/in_a_nutshell.jpg",
     "lib/public/images/jyurek.jpg",
     "lib/public/images/ken-arnold.jpg",
     "lib/public/images/leniwce_controller.png",
     "lib/public/images/leniwce_controller.svg",
     "lib/public/images/leniwiec.png",
     "lib/public/images/leniwiec.svg",
     "lib/public/images/martin-fowler.jpg",
     "lib/public/images/mislav.jpg",
     "lib/public/images/mvc.png",
     "lib/public/images/mvc.svg",
     "lib/public/images/pablo_picasso.jpg",
     "lib/public/images/pastie.png",
     "lib/public/images/rails3.png",
     "lib/public/images/rails3.svg",
     "lib/public/images/register-1.png",
     "lib/public/images/register-2.png",
     "lib/public/images/the_thinker.jpg",
     "lib/public/images/wesole_kontakty.jpg",
     "lib/public/javascripts/jquery.countdown-pl.js",
     "lib/public/javascripts/jquery.countdown.js",
     "lib/public/javascripts/ruby3.js",
     "lib/public/stylesheets/fonts/Cyklop-Italic.otf",
     "lib/public/stylesheets/icons/doc.png",
     "lib/public/stylesheets/icons/email.png",
     "lib/public/stylesheets/icons/external.png",
     "lib/public/stylesheets/icons/feed.png",
     "lib/public/stylesheets/icons/im.png",
     "lib/public/stylesheets/icons/pdf.png",
     "lib/public/stylesheets/icons/visited.png",
     "lib/public/stylesheets/icons/xls.png",
     "lib/public/stylesheets/ie.css",
     "lib/public/stylesheets/jquery.countdown.css",
     "lib/public/stylesheets/print.css",
     "lib/public/stylesheets/rails3.css",
     "lib/public/stylesheets/screen.css",
     "lib/public/stylesheets/src/grid.png",
     "lib/public/stylesheets/uv.css",
     "lib/rails3-tutorial.rb",
     "lib/views/ale-kino.rdiscount",
     "lib/views/answers.rdiscount",
     "lib/views/authentication.rdiscount",
     "lib/views/authorization.rdiscount",
     "lib/views/blog.rdiscount",
     "lib/views/caching.rdiscount",
     "lib/views/console.rdiscount",
     "lib/views/declarative-authorization.rdiscount",
     "lib/views/exercises.rdiscount",
     "lib/views/favicon.ico.rdiscount",
     "lib/views/firefox.rdiscount",
     "lib/views/fortune.rdiscount",
     "lib/views/heroku.rdiscount",
     "lib/views/i18n.rdiscount",
     "lib/views/intro.rdiscount",
     "lib/views/layout.rdiscount",
     "lib/views/layouts.rdiscount",
     "lib/views/main.rdiscount",
     "lib/views/pastie.rdiscount",
     "lib/views/prezentacje.txt",
     "lib/views/projekty.rdiscount",
     "lib/views/questions.rdiscount",
     "lib/views/ruby19.rdiscount",
     "lib/views/searching.rdiscount",
     "lib/views/security.rdiscount",
     "lib/views/slick-code.rdiscount",
     "lib/views/store.rdiscount",
     "lib/views/todo.rdiscount",
     "lib/views/wizja.rdiscount",
     "rails3-tutorial.gemspec"
  ]
  s.homepage = %q{http://github.com/wbzyl/rails3-tutorial}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rails3-tutorial}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Notatki do wykladu Architektura serwisow internetowych.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
      s.add_runtime_dependency(%q<ultraviolet>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-rdiscount>, ["~> 0.9"])
      s.add_runtime_dependency(%q<rack-codehighlighter>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<sinatra>, ["~> 0.9"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
      s.add_dependency(%q<ultraviolet>, [">= 0"])
      s.add_dependency(%q<sinatra-rdiscount>, ["~> 0.9"])
      s.add_dependency(%q<rack-codehighlighter>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<sinatra>, ["~> 0.9"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
    s.add_dependency(%q<ultraviolet>, [">= 0"])
    s.add_dependency(%q<sinatra-rdiscount>, ["~> 0.9"])
    s.add_dependency(%q<rack-codehighlighter>, [">= 0"])
  end
end

